version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: backend
      target: dev
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    environment:
      - DB_HOST=$DATABASE_HOST
      - DB_USERNAME=$DATABASE_USERNAME
      - DB_PASSWORD=$DATABASE_PASSWORD
      - DB_NAME=$DATABASE_NAME
      - DB_PORT=$DATABASE_PORT
    networks:
      - shared-network
  frontend:
    depends_on:
      - backend
    build:
      context: frontend
      target: dev
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 4001:3001
    environment:
      - PORT=3001
      - BACKEND_BASE_URL=$BACKEND_BASE_URL
    stdin_open: true
    tty: true
    networks:
      - shared-network
networks:
  shared-network:
