version: '3.8'

services:
  backend:
    restart: unless-stopped
    build:
      context: backend
      target: ${TARGET}
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    environment:
      - DB_HOST=${DATABASE_HOST}
      - DB_USERNAME=${DATABASE_USERNAME}
      - DB_PASSWORD=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
      - DB_PORT=${DATABASE_PORT}
      - JSON_RPC_PROVIDER_URL=${JSON_RPC_PROVIDER_URL}
      - CONTROLLER_PRIVATE_KEY=${CONTROLLER_PRIVATE_KEY}
      - DEPLOYER_CONTRACT_ADDRESS=${DEPLOYER_CONTRACT_ADDRESS}
      - TRON_FULL_HOST_URL=${TRON_FULL_HOST_URL}
      - TRON_PRO_API_KEY=${TRON_PRO_API_KEY}
  frontend:
    depends_on:
      - backend
    build:
      context: frontend
      target: ${TARGET}
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - $FRONTEND_PORT:3000
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=${NEXT_PUBLIC_BACKEND_BASE_URL}
      - NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS=${NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS}
      - TOKEN_CONTRACT_ADDRESS=${NEXT_PUBLIC_TOKEN_CONTRACT_ADDRESS}
    stdin_open: true
    tty: true
